[package]
name = "serval-charton"
version = "1.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
charton = { version = "0.5.8", features = ["png"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "4.5", features = ["derive"] }
polars = { version = "0.49", default-features = false }
polars-io = { version = "0.49", default-features = false, features = ["csv"] }

[build-dependencies]
winresource = "0.1"

[profile.release]
strip = "symbols"
